** def
#+BEGIN_SRC latex

        \def\hiya#1#2{Oh hiya hiya #1 and #2}
        \newcommand\Hiya[2][bill]{Oh hiya hiya #1 and #2 , }

        \hiya{Johd}{Brff}
        \Hiya{Brff}
        \Hiya[Johd]{Brff}
#+END_SRC
*** newcommand
#+BEGIN_SRC latex
  % no argument
  \newcommand{\R}{\mathbb{R}}

  % 1 arguments
  The set of real numbers are usually represented 
  by a blackboard bold capital r: \( \R \).

  \newcommand{\bb}[1]{\mathbb{#1}}

  Other numerical systems have similar notations. 
  The complex numbers \( \bb{C} \), the rational 
  numbers \( \bb{Q} \) and the integer numbers \( \bb{Z} \).


#+END_SRC
*** optional arguments
#+BEGIN_SRC latex
  \newcommand{\plusbinomial}[3][2]{(#2 + #3)^#1}
  % take 3 args, and first args default to ``2''

  To save some time when writing too many expressions 
  with exponents is by defining a new command to make simpler:

  \[ \plusbinomial{x}{y} \]

  And even the exponent can be changed

  \[ \plusbinomial[4]{y}{y} \]
#+END_SRC
*** renewcommand
#+BEGIN_SRC latex
\renewcommand{\S}{\mathbb{S}}

The Riemann sphere (the complex numbers plus $\infty$) is 
sometimes represented by \( \S \)
#+END_SRC
** dimen
#+begin_src tex
\newdimen\variable
\variable=42pt
The value is now \the\variable.
#+end_src
** newenvironment
*** synopsis
#+begin_src latex
{ \newenvironment{myEnvironmentName}
  [ <optional # of arguments, from 1 to 9> ]
  { <replacement text for each occurrence of \begin{myEnvironmentName}> }
  { <replacement text for each occurrence of \end{myEnvironmentName}> }}
  #+end_src
*** example
#+begin_src latex
\newenvironment{myHeartEnv}
  {\color{purple}{\heartsuit}\kern-2.5pt\color{green}{\heartsuit}}
  {\text{ forever}}

\begin{myHeartEnv}
\end{myHeartEnv}
#+end_src
** for loop
#+BEGIN_SRC latex

  \makeatletter
  \@for\sun:={rising,setting}\do{The sun is \sun.}
  \makeatother
  % sun is rising. sun is setting.
#+END_SRC

** class and pkg
*** What are the format?
class file : .cls
package : .sty
*** class
**** General structure
1. Identification::the file declares itself as a class written with the LaTeX2ε
   syntax.
2. Prelimirary_declaration::list dependencies
3. Options::declares and processes the options
4. Main Body
**** Identification
The two must-have commands:
#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{myclass}[2014/08/16 Example LaTeX class]
#+end_src
**** Prelimirary_declaration
#+begin_src latex
  \newcommand{\headlinecolor}{\normalcolor}
  \RequirePackage{xcolor}         %same as \usepackage but can appear before \documentclass
  \definecolor{slcolor}{HTML}{882B21}
#+end_src
**** Options
#+begin_src latex
  \DeclareOption{onecolumn}{\OptionNotUsed} %\OptionNotUsed means ignore this
                                  %option if the user tries to set the column
                                  %number to 1 

  % \DeclareOption{<option-name>}{<code-to-be-executed-when-the-option-is-on>}
  \DeclareOption{green}{\renewcommand{\headlinecolor}{\color{green}}}
  \DeclareOption{red}{\renewcommand{\headlinecolor}{\color{slcolor}}}
  \DeclareOption*{\PassOptionsToClass{\CurrentOption}{article}}
  % \Declareoption*{} handles every option not explicitly defined.
  \ProcessOptions\relax
  \LoadClass[twocolumn]{article}  %Use this article as base
#+end_src

 ~\PassOptionsToClass{}{}.~ Passes the option inside the first pair of braces to
 the document class set inside the second pair of braces. In the example, all
 unknown options will be passed to the article document class.
 
~\CurrentOption~ stores the name of the class option being handled at a
determined moment.
**** Main Body
#+begin_src latex
  \renewcommand{\maketitle}{%
      \twocolumn[%
          \fontsize{50}{60}\fontfamily{phv}\fontseries{b}%
          \fontshape{sl}\selectfont\headlinecolor
          \@title
          \medskip
          ]%
  }

  \renewcommand{\section}{%
      \@startsection
      {section}{1}{0pt}{-1.5ex plus -1ex minus -.2ex}%
      {1ex plus .2ex}{\large\sffamily\slshape\headlinecolor}%
  }

  % All class should define the following four
  \renewcommand{\normalsize}{\fontsize{9}{10}\selectfont}
  \setlength{\textwidth}{17.5cm}
  \setlength{\textheight}{22cm}
  \setcounter{secnumdepth}{0}
#+end_src
** math
*** calculate int + int -> int
#+begin_src latex
\documentclass{article}
\title{test}
\usepackage{geometry}\geometry{
  a4paper,
  total={170mm,257mm},
  left=20mm,
  top=20mm,
  }
  \author{Jianer Cong}
  \date{\today}
  \usepackage{pgfmath}
  \begin{document}
  \pgfmathparse{1+1}
  \def\myget#1.#2{#1}         %get the value before decimal
  % \def\v{ \myget({\pgfmathresult)} }
  Result: \pgfmathresult{}, Int result:
  % \myget1.2
  \expandafter\myget\pgfmathresult{}
  \end{document}
  #+end_src

# Local Variables:
# org-what-lang-is-for: "latex"
# End:
** counter
*** yours
#+begin_src latex
  \newcounter{somecounter}[anothercounter]
  \setcounter{somecounter}{number}
  \addtocounter{somecounter}{number}
  \stepcounter{somecounter}
  \refstepcounter{somecounter}    %makes \ref,\label aware of it

  % Access counter
  \arabic{somecounter}
  \roman{somecounter}
  \Roman{somecounter}
  \alph{somecounter}
  \Alph{somecounter}
  \fnsymbol{somecounter}
  \value{somecounter}

  % other counter
  \counterwithin{somecounter}{anothercounter}
  \counterwithout{somecounter}{anothercounter}
#+end_src
Example
#+begin_src latex
\newcounter{mycounter}
\setcounter{mycounter}{42}
You can now write \verb|\themycounter| to obtain \themycounter.
#+end_src
*** laTeX default
+ part
+ chapter
+ section
+ subsection
+ subsubsection
+ paragraph
+ subparagraph
+ page
For floats	
+ equation
+ figure
table
For footnotes	
+ footnote
+ mpfootnote
For the enumerate environment	
+ enumi
+ enumii
+ enumiii
+ enumiv


*** read and increment the counter
    #+BEGIN_SRC latex
    % Insert figure with caption in minipage 
\documentclass{article}


\begin{document}

\section{One section}
Hi
\section{Another section}
This is a dummy section with no purpose whatsoever but to contain text. 
This section has assigned the number \thesection.

\stepcounter{equation}          %increment the counter
\begin{equation}
  \label{1stequation}
  \int_{0}^{\infty} \frac{x}{\sin(x)}
\end{equation}

\end{document}
    #+END_SRC
*** get
#+BEGIN_SRC latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

\newcounter{example}[section]   %define a counter (renewed at each section)
% define an env
% use \refstepcounter to increment it , so that we can \ref and \label it
% use \theexample to access the counter
\newenvironment{example}[1][]{\refstepcounter{example}\par\medskip
  \textbf{Example~\theexample. #1} \rmfamily}{\medskip}

\begin{document}
This document will present...

\begin{example}\label{hi}
  This is the first example. The counter will be reset at each section.
\end{example}

Above is the example~\ref{hi}.
It can also be

example~\roman{example}
example~\arabic{example}
example~\Roman{example}
example~\Alph{example}
example~\alph{example}
example~\fnsymbol{example}

Use \texttt{$\backslash$value\{example\}} to access it in a numeric expression as in

\texttt{$\backslash$setcounter\{section\}\{$\backslash$value\{subsection\}\}}

Below is a second example

\begin{example}
  And here's another numbered example.
\end{example}

\section{Another section}
This is a dummy section with no purpose whatsoever but to contain text. 
This section has assigned the number \thesection.

\stepcounter{equation}
\begin{equation}
  \label{1stequation}
  \int_{0}^{\infty} \frac{x}{\sin(x)}
\end{equation}

\begin{example}
  This is the first example in this section. 
\end{example}

\end{document}
#+END_SRC
*** How label works
Well, \label is defined in the LaTeX kernel as

#+begin_src latex
\def\label#1{\@bsphack
  \protected@write\@auxout{}%
         {\string\newlabel{#1}{{\@currentlabel}{\thepage}}}%
  \@esphack}
  #+end_src
Note that (despite all the other things going on), it writes to the .aux file something that looks like this:
#+begin_src latex
\newlabel{<label>}{{<currentlabel>}{<page>}}
#+end_src
where <label> is what supply in the form \label{<label>} and <currentlabel> is
the current value of ~\@currentlabel~ - a macro that is usually updated whenever
you call ~\refstepcounter{<cntr>}~.

So, if \@currentlabel is not up-to-date according to the reference you're after,
then you'll obtain an incorrect reference. Most notably this happens when you
place a \label before \caption, since \caption increases some counter (figure or
table counter, say). <page> is the page on which the reference occurs within the
document and has the value of \thepage at that time - this could be anything set
out in the definition of \thepage, just for clarity.
