** sleep
#+begin_src python
  import time
  time.sleep(4)                   # 4 sec
#+end_src
** subprocess
#+begin_src python
import subprocess
s = subprocess.check_output(['cat','/etc/issue'],stderr=subprocess.STDOUT)
# s = subprocess.check_output(['echo','hi'],stderr=subprocess.STDOUT)
print(s.decode().strip())

#+end_src
** function
#+begin_src python
x = lambda a : a + 10
print(x(5))
#+end_src
** yaml
#+begin_src yaml
  rest:
    url: "https://example.org/primenumbers/v1"
    port: 8443
    prime_numbers: [2, 3, 5, 7, 11, 13, 17, 19]
#+end_src
#+begin_src python
import yaml

with open('config.yml', 'r') as file:
    prime_service = yaml.safe_load(file)

print(prime_service['prime_numbers'][0])
print(prime_service['rest']['url'])
#+end_src

** date
#+begin_src python
import datetime

x = datetime.datetime.now()
print(x) 
#+end_src

*** date output
#+begin_src python
  import datetime

  print('The Date Today is  :', datetime.datetime.today())

  date_today = datetime.date.today()
  print(date_today)
  print('This Year   :', date_today.year)
  print('This Month    :', date_today.month)
  print('Month Name:',date_today.strftime('%B'))
  print('This Week Day    :', date_today.day)
  print('Week Day Name:',date_today.strftime('%A'))

  # The Date Today is  : 2018-04-22 15:38:35.835000
  # 2018-04-22
  # This Year   : 2018
  # This Month    : 4
  # Month Name: April
  # This Week Day    : 22
  # Week Day Name: Sunday
#+end_src
*** datetime arithmetic
#+begin_src python
  import datetime

  #Capture the First Date
  day1 = datetime.date(2018, 2, 12)
  print('day1:', day1.ctime())

  # Capture the Second Date
  day2 = datetime.date(2017, 8, 18)
  print('day2:', day2.ctime())

  # Find the difference between the dates
  print('Number of Days:', day1-day2)


  date_today  = datetime.date.today()

  # Create a delta of Four Days
  no_of_days = datetime.timedelta(days=4)

  # Use Delta for Past Date
  before_four_days = date_today - no_of_days
  print('Before Four Days:', before_four_days )

  # Use Delta for future Date
  after_four_days = date_today + no_of_days
  print('After Four Days:', after_four_days )

  # day1: Mon Feb 12 00:00:00 2018
  # day2: Fri Aug 18 00:00:00 2017
  # Number of Days: 178 days, 0:00:00
  # Before Four Days: 2018-04-18
  # After Four Days: 2018-04-26
#+end_src
*** compare datetime
#+begin_src python
  import datetime

  date_today  = datetime.date.today()

  print('Today is: ', date_today)
  # Create a delta of Four Days
  no_of_days = datetime.timedelta(days=4)

  # Use Delta for Past Date
  before_four_days = date_today - no_of_days
  print('Before Four Days:', before_four_days )

  after_four_days =  date_today + no_of_days

  date1 = datetime.date(2018,4,4)

  print('date1:',date1)

  if date1 == before_four_days :
      print('Same Dates')
  if date_today > date1:
      print('Past Date')
  if date1 < after_four_days:
      print('Future Date')
  # Today is:  2018-04-22
  # Before Four Days: 2018-04-18
  # date1: 2018-04-04
  # Past Date
  # Future Date
    #+end_src
*** create date object
#+begin_src python
import datetime
y = datetime.date.fromisoformat('2019-12-04')
x = datetime.datetime(2020, 5, 17)

print(x) 
#+end_src

*** strftime() method
#+begin_src python
import datetime

x = datetime.datetime(2018, 6, 1)

print(x.strftime("%B")) 
#+end_src
https://www.w3schools.com/python/python_datetime.asp

** print

print(object(s), sep=separator, end=end, file=file, flush=flush)

** souce a file
#+begin_src python
exec(open('filename').read())
#+end_src
** Q&A
*** Encoding issue when reading lines from windows?
    #+begin_src python
      f = open('hi.txt', 'r', encoding = 'utf8')
      import locale
      local.getpreferredencoding()    # 'cp1252' on windows
    #+end_src
** string and numbers
*** basic
#+begin_src python
  a = 'Apple'
  b = 1.23
  m = '%s costs %d USD' % (a,b)

  # binary format
  bin(5)                          # 0b101
  bin(5).replace('0b','')         # 101
  # pad with 0
  bin(1).replace('0b','').zfill(4)  # 0001
#+end_src
Reverse string.
In this particular example, the slice statement [::-1] means start at the end of
the string and end at position 0, move with the step -1, negative one, which
means one step backwards.
#+begin_src python
txt = "Hello World" [::-1]
print(txt) 
#+end_src
*** parse
#+begin_src python
  int('101', 2)                   # ⇒ 5
  int('f',16)                     # ⇒ 15
  int('ff',16)                    # ⇒ 255
#+end_src
*** format
#+begin_src python
  '%x' % 12                       # c
  '%X' % 12                       # C
#+end_src
*** re
**** re.match: match from beginning
If zero or more characters at the *beginning* of string match the regular
expression pattern, return a corresponding match object.

Return ~None~ if the string does not match the pattern; note that this is
different from a zero-length match.
#+begin_src python
  bool(re.match('A','A1'))        # True
  bool(re.match('1','A1'))        # False
#+end_src
**** re.search: contains the pattern
Scan through string looking for the *first location* where the regular expression
pattern produces a match, and return a corresponding match object.
#+begin_src python
  import re

  step = 'A1'
  m = re.search('^([A-Z])([0-9]{1,2})$',step)
  if m:
      print(f'{m.group(1)}, {m.group(2)}')
  else:
      print('Not valid')
      # A, 1
  m.groups()                      # ('A','1')
    #+end_src

Return ~None~ if no position in the string matches the pattern; note that this is
different from finding a zero-length match at some point in the string.
**** re.fullmatch(pattern,string)
match the whole string ⇒ Match Object
#+begin_src python
  import re

  s = 'abcde'
  bool(re.fullmatch('bc',s))      # False
  bool(re.fullmatch('abcde',s))   # True
    #+end_src
**** re.sub(pattern, replacement, string): replace regexp
replace regexp
#+begin_src python
  re.sub(r'def\s+([a-zA-Z_][a-zA-Z_0-9]*)\s*\(\s*\):',
         r'static PyObject*\npy_\1(void)\n{',
         'def myfunc():')
  'static PyObject*\npy_myfunc(void)\n{'
       #+end_src
**** match object
#+begin_src python
  r = re.search('abc','abcyyyyabc')
  r.pos                           # 0
  r.start()                       # 0
  r.end()                         # 3
  r.span()                        # (0,3)
#+end_src

** collections
*** dic
#+begin_src python
  d = {'a':22,'b':44,'c':'na'}
  d['c']
  d['d'] = 23
  d.get('e','Not Found')
  'a' in d                        # True
  22 in d.values()                # True
  items(d)                        # list of pair
  d.keys()                            # list of keys

  bob2 = dict(zip(['name', 'job', 'age'], ['Bob', 'dev', 40])) # Zipping
  bob1 = dict(name='Bob', job='dev', age=40) # Keywords

  for k in sorted(d.keys()):
    print(k)

  # delete a key
  bob1.pop('name')
#+end_src
*** set
#+begin_src python
  thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
  myset = {"apple", "banana", "cherry"}
  thisset = {"apple", "banana", "cherry", "apple"}  # duplicated vals are ignored

  m = set({})
  m.add(1)
  1 in m                          # True
  m.discard(1)
  1 in m                          # False
  len(0)                          # 0
 #+end_src
*** ordered dict
#+begin_src python
  # A Python program to demonstrate working of OrderedDict
  from collections import OrderedDict

  print("This is a Dict:\n")
  d = {}
  d['a'] = 1
  d['b'] = 2
  d['c'] = 3
  d['d'] = 4

  for key, value in d.items():
    print(key, value)
  # a 1
  # c 3
  # b 2
  # d 4

  print("\nThis is an Ordered Dict:\n")
  od = OrderedDict()
  od['a'] = 1
  od['b'] = 2
  od['c'] = 3
  od['d'] = 4

  for key, value in od.items():
    print(key, value)
  This is a Dict:

  # This is an Ordered Dict:
  # a 1
  # b 2
  # c 3
  # d 4
#+end_src
*** sorted
#+begin_src python

  L = ["cccc", "b", "dd", "aaa"]
  print("Normal sort :", sorted(L))
  print("Sort with len :", sorted(L, key=len))

  # Normal sort : ['aaa', 'b', 'cccc', 'dd']
  # Sort with len : ['b', 'dd', 'aaa', 'cccc']


  x = [2, 8, 1, 4, 6, 3, 7]
  print("Sorted List returned :", sorted(x))
  print("Reverse sort :", sorted(x, reverse=True))
  print("\nOriginal list not modified :", x)
  # Sorted List returned : [1, 2, 3, 4, 6, 7, 8]
  # Reverse sort : [8, 7, 6, 4, 3, 2, 1]

  # Original list not modified : [2, 8, 1, 4, 6, 3, 7]
#+end_src
*** functools
**** reduce: reverse sort a string
#+begin_src python

# import the module
import functools
# initializing string
test_string = "geekforgeeks"
  
# printing original string
print("The original string : " + str(test_string))
  
# using sorted() + reduce() + lambda
# Reverse Sort a String
res = functools.reduce(lambda x, y: x + y,
                       sorted(test_string, 
                              reverse=True))
# print result
print("String after reverse sorting : " + str(res))
#+end_src
*** list
**** delete
#+begin_src python
  myList = [‘a’ , ‘b’ , ‘c’ , ‘d’ , ‘e’ , ‘f’ , ‘g’ , ‘h’ , ‘i’ , ‘j’ , ‘k’ , ‘l’]
  #delete the third item (index = 2)
  del myList[2]
  print (myList)
  # => [‘a’, ‘b’, ‘d’, ‘e’, ‘f’, ‘g’, ‘h’, ‘i’, ‘j’, ‘k’, ‘l’]

  #delete items from index 1 to 5-1 --------------------------------------------------
  del myList[1:5]
  print (myList)
  # => [‘a’, ‘g’, ‘h’, ‘i’, ‘j’, ‘k’, ‘l’]
  #delete items from index 0 to 3-1 --------------------------------------------------
  del myList [ :3]
  print (myList)
  # => [‘i’, ‘j’, ‘k’, ‘l’]
  #delete items from index 2 to end --------------------------------------------------
  del myList [2:]
  print (myList)
  # => [‘i’, ‘j’]
#+end_src
**** insert
#+begin_src python


  myList = [‘a’ , ‘b’ , ‘c’ , ‘d’]
  ‘c’ in myList
  myList = [‘a’ , ‘b’ , ‘c’ , ‘d’ , ‘e’]
  myList.insert(1, ‘Hi’)
  print (myList)
  # => [‘a’, ‘Hi’, ‘b’, ‘c’, ‘d’, ‘e’]

  #+end_src
**** pop()
#+begin_src python
  myList = [‘a’ , ‘b’ , ‘c’ , ‘d’ , ‘e’]
  #remove the third item
  member = myList.pop(2)
  print (member)
  # => c
  print (myList)
  # => [‘a’, ‘b’, ‘d’, ‘e’]

  #remove the last item
  member = myList.pop( )
  print (member)
  # => e
  print (myList)
  # => [‘a’, ‘b’, ‘d’]
#+end_src
**** index()
#+begin_src python
  l = [10,20]
  l.index(20)                      # 1
#+end_src

** work with file
*** write to file
#+begin_src python
  f = open('myfile.txt', 'a')
  f.write('\nThis sentence will be appended.')
  f.write('\nPython is here!')
  f.close()
#+end_src
** try except
*** raise and except
#+begin_src python
  try:
      f()
  except IndexError:
      print('Got exception')
  print('Continuing')

  
  try:
      raise IndexError
  except IndexError:
      print('Got exception')
  print('Continuing')

  try:
      f()
  except Exception as X:
      print(X)
#+end_src
*** define your own exception by inheriting the Exception
#+begin_src python
  class MyError(Exception): pass
  def h():
      raise MyError()

  try:
      h()
  except MyError:
      print('Got MyError')
#+end_src
*** Catch all exceptions
except clauses that list no exception name ( except: ) catch all exceptions not pre-
viously listed in the try statement.
#+begin_src python
  try:
      action()
  except NameError: # Handle NameError
      ...
  except IndexError: # Handle IndexError
      ...
  except: # Handle all other exceptions
      ...
#+end_src
* End

# Local Variables:
# org-what-lang-is-for: "python"
# End:
