version: '3'

services:
 mongo:
  image: mongo
  ports:
  - 27017:27017

 backend:
  build:
   context: ./backend
  ports:
  - 9001:9001
  environment:
    MONGO_HOST: mongo
  depends_on:
  - mongo

 auth:
  build:
   context: ./backend-auth
  ports:
  - 9002:9002
