
exec-suffixes                           ;(".exe" ".com" ".bat" ".cmd" ".btm" "")

;; the name of a directory that contains programs that come with GNU Emacs and are intended for Emacs to invoke
exec-directory                          ;"c:/MyFun/eMACS/x86_64/libexec/emacs/27.1/x86_64-w64-mingw32/"

exec-path                               ;("c:/Program Files/WindowsApps/Microsoft.PowerShell_7.1.3.0_x64__8wekyb3d8bbwe" "c:/Windows/system32" "c:/Windows" "c:/Windows/System32/Wbem" "c:/Windows/System32/WindowsPowerShell/v1.0" "c:/Windows/System32/OpenSSH" "c:/Program Files/Common Files/Autodesk Shared" "c:/Program Files (x86)/Toshiba/Bluetooth Toshiba Stack/sys" "c:/Program Files (x86)/Toshiba/Bluetooth Toshiba Stack/sys/x64" "c:/Program Files (x86)/EPA SWMM 5.1.014" "c:/MyData/Yangon/Swmm" "c:/Program Files/Git/cmd" "c:/Program Files/R/R-4.0.3/bin" "c:/MyFun/eMACS/x86_64/bin" "c:/Program Files/Git/bin" "c:/Program Files/RStudio/bin/pandoc" "c:/ProgramData/chocolatey/bin" "c:/Program Files/dotnet" "c:/Users/congj/AppData/Local/Microsoft/WindowsApps" "c:/MikiTex/miktex/bin/x64" "c:/Users/congj/AppData/Local/GitHubDesktop/bin" "c:/Users/congj/AppData/Local/GitHubDesktop/app-2.6.1/resources/app/git/mingw64/bin" "c:/Users/congj/AppData/Local/Pandoc" "c:/ProgramData/Microsoft/Windows/Start Menu/Programs/GNU Octave 6.2.0" "c:/Users/congj/.dotnet/tools" "c:/Program Files (x86)/Microsoft/Edge/Application" "c:/Program Files/WindowsApps/Microsoft.PowerShell_7.1.4.0_x64__8wekyb3d8bbwe" "c:/Program Files (x86)/VMware/VMware Workstation/bin" "c:/Program Files (x86)/eudic" "c:/Users/congj/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/Scripts" "c:/Program Files/CMake/bin" "c:/MyFun/eMACS/x86_64/libexec/emacs/27.1/x86_64-w64-mingw32")
(exec-path)                             ;("c:/Program Files/WindowsApps/Microsoft.PowerShell_7.1.3.0_x64__8wekyb3d8bbwe" "c:/Windows/system32" "c:/Windows" "c:/Windows/System32/Wbem" "c:/Windows/System32/WindowsPowerShell/v1.0" "c:/Windows/System32/OpenSSH" "c:/Program Files/Common Files/Autodesk Shared" "c:/Program Files (x86)/Toshiba/Bluetooth Toshiba Stack/sys" "c:/Program Files (x86)/Toshiba/Bluetooth Toshiba Stack/sys/x64" "c:/Program Files (x86)/EPA SWMM 5.1.014" "c:/MyData/Yangon/Swmm" "c:/Program Files/Git/cmd" "c:/Program Files/R/R-4.0.3/bin" "c:/MyFun/eMACS/x86_64/bin" "c:/Program Files/Git/bin" "c:/Program Files/RStudio/bin/pandoc" "c:/ProgramData/chocolatey/bin" "c:/Program Files/dotnet" "c:/Users/congj/AppData/Local/Microsoft/WindowsApps" "c:/MikiTex/miktex/bin/x64" "c:/Users/congj/AppData/Local/GitHubDesktop/bin" "c:/Users/congj/AppData/Local/GitHubDesktop/app-2.6.1/resources/app/git/mingw64/bin" "c:/Users/congj/AppData/Local/Pandoc" "c:/ProgramData/Microsoft/Windows/Start Menu/Programs/GNU Octave 6.2.0" "c:/Users/congj/.dotnet/tools" "c:/Program Files (x86)/Microsoft/Edge/Application" "c:/Program Files/WindowsApps/Microsoft.PowerShell_7.1.4.0_x64__8wekyb3d8bbwe" "c:/Program Files (x86)/VMware/VMware Workstation/bin" "c:/Program Files (x86)/eudic" "c:/Users/congj/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/Scripts" "c:/Program Files/CMake/bin" "c:/MyFun/eMACS/x86_64/libexec/emacs/27.1/x86_64-w64-mingw32")




