** Art and Misc
*** audio-recorder
https://www.maketecheasier.com/record-system-sound-linux/
#+begin_src bash
  sudo apt install audacity pavucontrol

#+end_src

*** AB repeat
#+begin_src bash
  sudo apt install vlc
#+end_src
View > Advanced Controls
*** pdf to png
    #+begin_src bash
      sudo apt install poppler-utils
      # Convert all page of doc.pdf png
      pdftoppm -png doc.pdf my_out
      # ⇒ my_out-1.png, my_out-2.png,...

      # Convert page 5 to 15 of pdf to png
      pdftoppm -png -f 5 -l 15 doc.pdf my_out

      # Change dpi from 150(default) to 300
      pdftoppm -png -rx 300 -ry 300 doc.pdf my_out
    #+end_src
*** Audio
#+BEGIN_SRC bash
  speaker-test
  alsamixer                       # on pi
  aplay hi.wav
#+END_SRC
*** firefox not playing video
 #+begin_src bash
sudo apt install ffmpeg
 #+end_src
*** install font from ttf files
#+begin_src bash
  sudo mkdir /usr/share/fonts/truetype/SourceCodePro
  sudo mv *.ttf /usr/share/fonts/truetype/SourceCodePro/
  ls  /usr/share/fonts/truetype/SourceCodePro
  fc-cache -f -v
  #+end_src
*** Get the SourceCodePro
#+begin_src bash
git clone https://github.com/adobe-fonts/source-code-pro.git SourceCodePro
cd SouceCodePro/TTF
sudo mkdir /usr/share/fonts/truetype/SourceCodePro/
sudo mv *.ttf /usr/share/fonts/truetype/SourceCodePro/
ls  /usr/share/fonts/truetype/SourceCodePro
fc-cache -f -v
cd ../..
rm -rf SourceCodePro

#+end_src
*** read epub
#+begin_src bash
  sudo apt install gnome-books
#+end_src
*** play video
#+begin_src bash
  sudo apt install vlc
#+end_src
*** avi to mp4
#+begin_src bash
  ffmpeg -i 'input.avi' out.mp4

#+end_src
** Blender Q&A
*** sea and submarine transparency dosen't show up correctly
sea.materialProperties.settings.blendMode='Alpha Blend'
submarine.materialProperties.settings.blendMode='Opaque'
*** link mesh and its animation?
put the mesh in to a collection and links it.
*** let obj follow path
+ make path
+ make obj
+ select obj
+ select path
+ Ctrl-P (parent) > follow path
+ animate the path.PathAnimation.EvaluationTime
  (maybe clear the keyframes for it first, so you
  can animate the object's movement manually, and
  then let it follow the path.)
*** timeline shortcuts
+ ctl-midMouseCLick-drag :: zoom
+ shf-scroll :: move Y
+ ctl-scroll :: move X
+ ctl-RMC :: add points
+ left-click :: box selects

+ H :: hide this
+ Shf-H :: solo this
+ Alt-H :: unhide all

+ select the f-curve + shf-E :: Extrapolation Mode
*** dope sheet
+ E :: extend key frames
+ Shf-T :: slide (proportionlly extend)
+  S :: scale
*** Action and Non-liner-editting (NLE)
+ NLE is the last place you compose animations
+ You first make some ani in dope sheet and then
  in curve-editor. Then you make it an 'Action'
  and push it to the NLE stack.
+ After you have pushed your action, it's not in
  the dope sheet anymore, but it can be reused by
  other objects
*** Add Node hooks
in edit mode, select the vertices and then ctl-H
** Packages
*** Snap
#+begin_src bash
  sudo snap install hello
  hello
  sudo snap refresh
  ls /snap
  sudo snap remove hello
 #+end_src
** Chinese
  #+begin_src bash
    sudo apt-get install ibus-pinyin
    ibus restart
  #+end_src
  
* End
# Local Variables:
# org-what-lang-is-for: "bash"
# fill-column: 50
# End:
