** Keys for windows
Virtual desktop:
 + win-ctr-Left/Right :: switch between virtual desktop
 + Win + CTRL + D :: Create a new desktop.
 + Win + CTRL + F4:: Close the current desktop.
 + win + TAB :: Show desktop
** Windows terminal
*** panes
    + C-S-W :: close the pane
    + M-S-+ :: split pane right
    + M-S-- :: split pane below
** excel
*** Export csv but it's delimited by ";"
    Something wrong with the system local
   Control Panel > change data,time,number format > Additional settings
*** VBA
#+begin_src visualbasic
Function incr(x)
incr = x + 1
End Function
#+end_src
** VS 
*** add reference to csproj in other dir with msbuild?
    #+begin_src pwsh
 dotnet add reference ..\mylib\hi.csproj
 msbuild -restore:true
    #+end_src
*** What does Add-Existing-Item in VS project explorer do ?
    It just copy-paste the file you specified to the project folder..
*** VS2022 Error On start
+ run as Admin
** Windows troubleshoot
*** msi电脑外接显示器没反应

概述： 尝试用HDMI线外接笔记本电脑到显示器，但检测不到。
换了一个笔记本电脑连接却发现可以说明显示器没有坏而且input接口没有坏。

解决方案：
1. Find the model and series number of the laptop.
2. Go to the MSI official website, download and install the *NVIDIA graphics
   driver* for this model and series.
** clash for windows Q&A
*** use clash Proxy in cmd
#+begin_src powershell
  Invoke-RestMethod google.com -Proxy http://localhost:7890 -OutFile m.html
#+end_src
** Record Audio
+ 加Nuget Extension
+ 用Nuget 加包
#+begin_src csharp
   using NAudio.Wave;

  string outputFilePath = @"C:\Users\congj\Desktop\hi.wav";

  WasapiLoopbackCapture CaptureInstance = new WasapiLoopbackCapture();
  WaveFileWriter RecordedAudioWriter = new WaveFileWriter(outputFilePath, CaptureInstance.WaveFormat);

  CaptureInstance.DataAvailable += (s, a) =>
  {
      RecordedAudioWriter.Write(a.Buffer, 0, a.BytesRecorded);
      //Console.WriteLine("new data available");
  };

  // When the Capturer Stops
  CaptureInstance.RecordingStopped += (s, a) =>
  {
      RecordedAudioWriter.Dispose();
      RecordedAudioWriter = null;
      CaptureInstance.Dispose();
  };

  CaptureInstance.StartRecording();
  Console.WriteLine("Recording started, press any key to stop");

  Console.ReadLine();
  CaptureInstance.StopRecording();
  Console.WriteLine("Recording stopped");

#+end_src
Next in the shell
#+begin_src powershell
lame .\hi.wav .\fr.mp3
#+end_src
** Make bootable disk
+ rufus
Or use dd.exe
Remember in the BIOS setting enable lagacy-compatble mode, not just UEFI-mode.
** wsl
#+begin_src powershell
  # list the installable distro in wsl
  wsl --list --online
  # install the distro Ubuntu 22.04
  wsl --install -d Ubuntu-22.04
  # set the default distro to Ubuntu 22.04
  wsl --set-default Ubuntu-22.04
  # start the default distro
  wsl
  # terminate the VM 
  wsl --shutdown
  # remove a distro
  wsl --unregister Ubuntu-22.04
  # list the distro
  wsl --list --verbose
#+end_src
